### ISSUE TITLE
bug: Drawer component of modal hides overflow

### ISSUE THREAD

**Issue by ieedan** [shyakadavis/geist#30]
Currently when using modal component when it is in dialog state content will not overflow to scroll.

![image](https://github.com/user-attachments/assets/e53fb21f-f83f-4613-afe3-ffc030ea9494)
(Don't judge me I use edge at work)

**Comment by shyakadavis** [comment]
Thanks for reporting. I actually left it as a to-do
https://github.com/shyakadavis/geist/blob/8be8260f4623de84863743481a5f4137558d411d/src/lib/components/ui/modal/modal-content.svelte#L36 

I just got lazy. 😅 Will look over it tomorrow if I have some time.

> (Don't judge me I use edge at work)

No judgment from me. (Loyal Firefox user here 😅)
