### ISSUE TITLE
bug: Command drawer is broken on mobile

### ISSUE THREAD

**Issue by ieedan** [shyakadavis/geist#69]
I should've probably tested this more thoroughly when reviewing but currently the drawer doesn't work on mobile. 

The overflow is hidden and there are a few styling issues.

![image](https://github.com/user-attachments/assets/d6a83c48-5117-43dc-9ebe-48bcc9b289af)

**Comment by shyakadavis** [comment]
Def going to make some time this weekend to close this and #30
Thanks for reporting.
